
// USER 
export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

export const GET_USER_REPOS_REQUEST = 'GET_USER_REPOS_REQUEST';
export const GET_USER_REPOS_SUCCESS = 'GET_USER_REPOS_SUCCESS';
export const GET_USER_REPOS_FAILURE = 'GET_USER_REPOS_FAILURE';

export const RESET_USER = 'RESET_USER';

// LOADING
export const LOADING_TRUE = 'LOADING_TRUE';
export const LOADING_FALSE = 'LOADING_FALSE';